# Generated by Django 5.0.2 on 2024-02-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='rate',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='code',
            new_name='from_currency',
        ),
        migrations.AddField(
            model_name='currency',
            name='to_currency',
            field=models.CharField(default=0, max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
