# Generated by Django 5.0.2 on 2024-02-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_rename_rate_currency_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='convert_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
