# Generated by Django 5.0.2 on 2024-02-27 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0003_currency_convert_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='convert_amount',
        ),
    ]
