# Use a imagem base do Python
FROM python:3.8-slim

# Configuração do ambiente
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Criação e definição do diretório de trabalho
WORKDIR /app

# Copie apenas o requirements.txt inicialmente para aproveitar o cache
COPY requirements.txt .

# Instale as dependências
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copie o restante do código para o contêiner
COPY . .

# Garanta que o manage.py tenha permissões de execução
RUN chmod +x manage.py

# Comando para executar a aplicação
CMD ["./manage.py", "runserver", "0.0.0.0:8000"]
